# 节点配置
node:
  startBlockHeight: 720609 # 初始区块

# redis相关key配置
redisKey:
  chainId: 50
  tokenId: 10

# 日志配置
log:
  fileLog:
    path: Logs/
    level: info
    enable: true
  conroseeLog:
    level: info
    enable: true
  asyncWrite: false
  enableContractLog: true

# redis配置
redis: redis://:@127.0.0.1:6379/0

# 钱包路径
walletPath: ./keyStore/

# nginx转发后的路由
sockPath: 47.240.127.63:10002

# genesis file
genesisPath: ./genesis/test_genesis.json


# https://docs.oasis.dev/oasis-core-ledger/usage/transactions
gasLimit: 1252
fee: 0
